### ISSUE TITLE
scatter_max fails with Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` on GPU

### ISSUE THREAD

**Issue by mmjb** [rusty1s/pytorch_scatter#222]
Heya,

We (me + @mallamanis) have a somewhat strange but reproducible-for-us problem with `scatter_max` (at least - it's the only `torch-scatter` operation we are using right now) in some internal code that I sadly can't easily share. Concretely, we get
```
2021-05-23 16:39:24 /pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: operator(): block: [1,0,0], thread: [32,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
2021-05-23 16:39:24 /pytorch/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: operator(): block: [1,0,0], thread: [33,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
[...]
2021-05-23 16:39:24   File "something.py", line 20, in some_fn:
2021-05-23 16:39:24     max_value_per_sample = torch_scatter.scatter_max(src.float(), index, dim=dim)[0]
2021-05-23 16:39:24 RuntimeError: The following operation failed in the TorchScript interpreter.
2021-05-23 16:39:24 Traceback of TorchScript (most recent call last):
2021-05-23 16:39:24   File "/usr/local/lib/python3.8/dist-packages/torch_scatter/scatter.py", line 79, in scatter_max
2021-05-23 16:39:24         out: Optional[torch.Tensor] = None,
2021-05-23 16:39:24         dim_size: Optional[int] = None) -> Tuple[torch.Tensor, torch.Tensor]:
2021-05-23 16:39:24     return torch.ops.torch_scatter.scatter_max(src, index, dim, out, dim_size)
```
Environment is a docker container built using this:
```
RUN python3.8 -m pip install --no-cache-dir torch==1.8.1+cu101 torchvision==0.9.1+cu101 torchaudio==0.8.1 -f https://download.pytorch.org/whl/torch_stable.html
RUN python3.8 -m pip install --no-cache-dir --upgrade torch-cluster torch-scatter torch-sparse torch-spline-conv -f https://pytorch-geometric.com/whl/torch-1.8.0+cu101.html
```
The executing host has CUDA11 and the driver version 450.80.02.

Here's some bizarre extra information:
* It's fine on CPU.
* This happens during training during the second (!) epoch or even later
* It's fine when setting `CUDA_LAUNCH_BLOCKING=1`
* Happens on P100s, but it's fine on V100s (as far as we could observe so far)

My best guess here is that the scatter kernel is reading garbag-y data for the index tensor.  The fact that `CUDA_LAUNCH_BLOCKING=1` makes this go away seems to point to the idea that maybe there's an issue with the kernel reading stale data for index tensor. The code roughly looks like this (inlined a bit relative to the stacktrace source to make more readable):
```
candidate_scores = self._scoring_mlp(candidates).squeeze(-1)
sample_arange = torch.arange(num_samples, dtype=torch.int64, device=candidate_to_sample_idx.device)
candidate_to_sample_idx = torch.cat((candidate_to_sample_idx, sample_arange)).contiguous()
max_value_per_sample = torch_scatter.scatter_max(
  torch.cat([candidate_scores , self._learnable_score.repeat(num_samples)]).float(),
  candidate_to_sample_idx ,
  dim=-1,
)[0]
```
My best theory here is that the computation of the index tensor may not have finished / memory has not been written back properly when the scatter kernel starts reading things. Any ideas what to try here / how to debug this?

**Comment by rusty1s** [comment]
Thanks for reporting, this is interesting. This looks indeed like an unfinished memory write, but I cannot explain myself why this should be the case. IMO, `scatter_max` waits for all previous CUDA computation to be completed. It's also weird that this does only happen on P100s.

It would be great if you could further test the following:

* Does the same error happen when using `scatter_add`?
* Does the error happen when calling `torch.cuda.synchronize()` before the `scatter_max` call?

**Comment by mallamanis** [comment]
I include below a script that seems to almost always replicate the issue in a few settings we tried (K80, P100, Torch 1.7.0/1.8.0, CUDA 10.2/11.1 ). There are a few options/comments inside the script that expose a few options. 

* The bug seems to appear _only_ when multi-threading and GPUs are used. In the script, one thread transfers data, the other applies a `scatter_max` operation.
* The more “busy” the GPU, the easier that the script triggers the bug.
* The bug seems to have to do with how the array storing the results of scatter_max is allocated. If `dim_size` is passed then the bug seems to vanish!
* The bug seems to also happen when `CUDA_LAUNCH_BLOCKING=1` but more rarely. This is why we originally thought that this solved the problem.
* `scatter_sum` (since it's delegate to core PyTorch) seems to be unaffected.


```python
from dpu_utils.utils import ThreadedIterator
from random import randint
from tqdm import trange
import torch
from torch_scatter import scatter_max, scatter_sum, scatter_log_softmax

# device = torch.device("cpu")  # No exception
device = torch.device("cuda:0")


def get_data():
    for _ in trange(200000):
        num_segments = randint(20, 5000)
        num_elements = num_segments + randint(20, 10000)
        src = torch.randn(size=(num_elements,), device=device)

        # Both version A and version B trigger the bug, but different exceptions are thrown.
        # Version A
        segments = torch.randint(low=0, high=num_segments-1, size=(num_elements,), device=device)

        # Version B
        #segments = torch.randint(low=0, high=num_segments-1, size=(num_elements-num_segments,), device=device)
        #segments = torch.cat((torch.arange(num_segments, device=device), segments))
        yield num_segments, src, segments

enable_multithreading = True  # Only when True the bug seems to be triggered


for num_segments, src, segments in ThreadedIterator(get_data(), max_queue_size=1, enabled=enable_multithreading):
    out = scatter_log_softmax(src, segments)  # Throws
    # out = scatter_max(src, segments)  # Also throws (slightly different error)
    # out = scatter_max(src, segments, dim_size=num_segments)  # Does *not* throw
    # out = scatter_sum(src, segments)  # Does *not* throw (delegated to PyTorch internal function)
```

**Comment by rusty1s** [comment]
Thanks for digging into this and for the valuable code to reproduce :)

I fixed the issue in master (by replacing `cudaMemcpy` calls with PyTorch `cpu()` calls, see [here](https://github.com/rusty1s/pytorch_scatter/commit/19a94a9155a7608b03e089c1a0797b338c15c691). This fixes the issue for me, although I'm still not sure what's causing the error in the first place.

**Comment by mallamanis** [comment]
Thanks a lot for looking into this and fixing it! We tested all relevant code and the error is gone. 🚀

**Comment by rusty1s** [comment]
New wheels are now also available with the fix :)

**Comment by minrui-hust** [comment]
which wheel solves the issue, I download the lastest 2.0.7, the issue still exists. 
I use 4*1080ti, after 17 epoch, this error happens
